const labels: Record<string, string> = {
  ready: "就绪",
  available: "可用",
  unavailable: "不可用",
  wechat_window_unavailable: "微信窗口不可用",
  not_ready: "未就绪",
  not_active: "未启用",
  not_configured: "未配置",
  disconnected: "未连接",
  disabled: "已停用",
  active: "进行中",
  completed: "已完成",
  done: "已完成",
  failed: "失败",
  error: "错误",
  warning: "警告",
  invalid: "无效",
  success: "成功",
  pending: "待处理",
  processing: "处理中",
  running: "运行中",
  queued: "排队中",
  sending: "发送中",
  sent: "已发送",
  send_unknown: "发送状态未知",
  ready_to_send: "待发送",
  stopped: "已停止",
  waiting_confirmation: "等待确认",
  needs_action: "需要处理",
  needs_feedback: "等待反馈",
  needs_human: "需要人工处理",
  blocked: "受阻",
  retryable: "可重试",
  unverified: "未验证",
  verified: "已验证",
  resolved: "已解决",
  approved: "已批准",
  rejected: "已拒绝",
  confirmed: "已确认",
  cancelled: "已取消",
  canceled: "已取消",
  executed: "已执行",
  skipped: "已跳过",
  not_started: "未开始",
  over_due: "已逾期",
  stale: "数据过期",
  no_action: "无需处理",
  draft: "草稿",
  loading: "加载中",
  refreshing: "刷新中",
  degraded: "状态降级",
  screen_locked: "屏幕已锁定",
  permission_required: "需要权限",
  unknown: "未知",
};

const tones: Record<string, "success" | "progress" | "warning" | "danger" | "neutral"> = {
  ready: "success",
  available: "success",
  active: "success",
  completed: "success",
  done: "success",
  sent: "success",
  resolved: "success",
  approved: "success",
  confirmed: "success",
  executed: "success",
  verified: "success",
  success: "success",
  healthy: "success",
  ok: "success",
  running: "progress",
  processing: "progress",
  sending: "progress",
  checking: "progress",
  pending: "warning",
  warning: "warning",
  queued: "warning",
  waiting_confirmation: "warning",
  ready_to_send: "warning",
  needs_action: "warning",
  needs_feedback: "warning",
  needs_human: "warning",
  retryable: "warning",
  send_unknown: "warning",
  unverified: "warning",
  stale: "warning",
  degraded: "warning",
  permission_required: "warning",
  not_configured: "warning",
  unavailable: "danger",
  wechat_window_unavailable: "danger",
  screen_locked: "danger",
  not_ready: "danger",
  disconnected: "danger",
  failed: "danger",
  error: "danger",
  invalid: "danger",
  blocked: "danger",
  rejected: "danger",
  over_due: "danger",
  stopped: "neutral",
  cancelled: "neutral",
  canceled: "neutral",
  skipped: "neutral",
  not_started: "neutral",
  disabled: "neutral",
  not_active: "neutral",
  no_action: "neutral",
  draft: "neutral",
  loading: "progress",
  refreshing: "progress",
  unknown: "neutral",
};

export function StatusBadge({ value }: { value: string }) {
  const key = value.trim().toLowerCase().replace(/\s+/g, "_");
  const label = labels[key] || value || "未提供";
  const tone = tones[key] || "neutral";
  return <span className={`status-badge status-${tone}`} data-status={key || "unknown"}>{label}</span>;
}
