// Local visual fixture only. Every API request is handled in memory.
import {createRoot} from "react-dom/client";
import {BrowserRouter} from "react-router-dom";
import {EmailPage} from "../pages/EmailPage";
import "../styles.css";
const scenario=new URLSearchParams(location.search).get("scenario") || "ready";
let version=1;
let mode=scenario==="model"?"model_primary":"agent_primary";
const categoryNames=[["work","工作"],["human_resources","人事"],["legal","法务"],["financing","融资"],["personal","个人"],["notification","通知"],["external_billing","外部账单"],["shopping","购物"]];
let configs=categoryNames.map(([category_key,display_name])=>({category_key,display_name,core_description:display_name+"相关事务，按邮件业务目的分类。",include:["需要处理的"+display_name+"事项","来自相关合作方的材料与进展"],exclude:["相邻类别的日常通知，应归入通知","私人活动，应归入个人"],description_version:"description-v1",config_version:"config-v1",threshold:.95,enabled:true,actions:["move"],action_parameters:{},updated_at:"2026-09-08T12:00:00Z",bindings:[{account_id:"fixture@example.test",provider_folder_id:"folder-"+category_key,provider_folder_name:display_name,binding_status:"active",last_verified_at:"2026-09-08T12:00:00Z"}]}));
let rows=Array.from({length:55},(_,i)=>({id:String(8423079112545370100n+BigInt(i)),subject:["合同审阅与项目推进 —— 长主题与中文 English mixed subject 用于密度检查","本周产品进展和下一阶段验收","外部账单已开具，请查收"][i%3],sender:"合作伙伴 "+(i+1)+" <partner@example.test>",preview:"项目资料已更新，请核对交付进度、负责人及需要进一步确认的问题。",received_at:"2026-09-08T12:30:00Z",category:categoryNames[i%8][0],confidence:.87,margin:.2,probabilities:{work:.87,legal:.13},classification_source:"agent",config_version:"config-v1",description_version:"description-v1",model_version:"email-embedding-mlp-fixture-v3",important:i%3===0?true:i%3===1?false:null,provider_classification:{state:"categorized",category_key:categoryNames[i%8][0],important:i%3===0},current_action_plan_id:"plan-"+i,action_plan:{action_plan_id:"plan-"+i,action_plan_version:1,actions:["move"]},attachment_metadata:[{filename:"合同.pdf",mime_type:"application/pdf",size_bytes:253952,inline:false}],status:"processed",created_at:"",updated_at:""}));
const models=Array.from({length:5},(_,i)=>({model_id:"email-embedding-mlp-2026090"+(i+1)+"T120000Z-abcdef0"+i,status:i===4?"candidate":"superseded",trained_at:"2026-09-0"+(i+1)+"T12:00:00Z",metrics:i===2?null:{accuracy:.9+i*.02,macro_f1:.9+i*.02,categories:{work:{precision:.98,recall:.96,f1:.97,support:37,accepted_precision:.99,accepted_hits:30,independent_groups:25,threshold:.95}},important:{precision:.98,recall:.97,f1:.97,accepted_precision:.99}},evaluation:i===2?null:{protocol:"email-folder-heldout-v1",test_digest:i>2?"test-b":"test-a",comparability_key:i>2?"group-b":"group-a"},compatibility:{enabled_categories:["work","legal"],description_version:"description-v1",embedding_revision_reference:"embedding-fixture-v1"},split_counts:{train:180,validation:50,test:50},head_timing_percentiles_ms:{p50:1,p95:2,p99:3},end_to_end_latency_ms:i===2?null:{p50:100,p95:200,p99:300},integrity_status:"verified",artifact_sha256:"a".repeat(64),training_snapshot_id:"fixture-snapshot-"+i}));
const histories=configs.map((config,index)=>({revision_id:index+1,category_key:config.category_key,config_version:config.config_version,description_version:config.description_version,created_at:config.updated_at,config:structuredClone(config)}));
let promotion={macro_f1_min:.95,category_precision_min:.95,category_validation_samples_min:20,p95_latency_max_ms:500,config_version:"promotion-v1"};
function learning(){return {runtime:{mode,active_model_id:mode==="model_primary"?models[4].model_id:null,candidate_model_id:models[4].model_id,candidate_ready:scenario!=="agent"&&mode==="agent_primary",toggle_enabled:scenario!=="agent"||mode==="model_primary"},promotion_gate:{config:promotion,promotion_eligible:scenario!=="agent",checks:[{key:"macro_f1",actual:scenario==="agent"?.8:.98,target:promotion.macro_f1_min,operator:">=",passed:scenario!=="agent",reason:scenario==="agent"?"threshold_not_met":"passed"},{key:"category_precision:work",actual:.98,target:promotion.category_precision_min,operator:">=",passed:true,reason:""},{key:"category_validation_samples:work",actual:25,target:promotion.category_validation_samples_min,operator:">=",passed:true,reason:""},{key:"p95_latency",actual:200,target:promotion.p95_latency_max_ms,operator:"<=",passed:true,reason:""}]},pending_examples:22,models:[],staged_models:models,mode_transitions:[],registry_issues:[]};}
window.fetch=async(input,init)=>{
  const url=new URL(String(input),location.origin);
  const path=url.pathname;
  const method=init?.method || "GET";
  const body=init?.body?JSON.parse(String(init.body)):{};
  let result:unknown;
  if(path==="/api/console/email/learning")result={ok:true,learning:learning()};
  else if(path==="/api/console/email/runtime-mode"&&method==="PUT"){mode=body.mode;result={ok:true,...learning()};}
  else if(path==="/api/console/email/promotion-config"&&method==="PUT"){promotion={...body,config_version:"promotion-v"+(++version)};result={ok:true,config:promotion};}
  else if(path==="/api/console/email/config"&&method==="GET")result={items:configs};
  else if(path.startsWith("/api/console/email/config/")&&path.endsWith("/history"))result={ok:true,items:histories.filter(item=>item.category_key===path.split("/")[5])};
  else if(path==="/api/console/email/config"&&method==="POST"){const item={...configs[0],...body,config_version:"config-v"+(++version),description_version:"description-v"+version};configs=[...configs,item];histories.push({revision_id:histories.length+1,category_key:item.category_key,config_version:item.config_version,description_version:item.description_version,created_at:item.updated_at,config:structuredClone(item)});result={ok:true,item};}
  else if(path.startsWith("/api/console/email/config/")&&method==="PUT"){const key=path.split("/").at(-1);configs=configs.map(item=>item.category_key===key?{...item,...body,config_version:"config-v"+(++version),description_version:"description-v"+version}:item);const item=configs.find(item=>item.category_key===key)!;histories.push({revision_id:histories.length+1,category_key:item.category_key,config_version:item.config_version,description_version:item.description_version,created_at:item.updated_at,config:structuredClone(item)});result={ok:true,item};}
  else if(path==="/api/console/email/classifications"){const page=Number(url.searchParams.get("page")),size=Number(url.searchParams.get("page_size"));result={items:rows.slice((page-1)*size,page*size),meta:{total:rows.length,page,page_size:size,has_more:page*size<rows.length,next_cursor:"",snapshot_at:"2026-09-08T12:30:00Z"}};}
  else if(path.startsWith("/api/console/email/classifications/")){const id=path.split("/")[5];const item=rows.find(row=>row.id===id);if(method==="POST"){rows=rows.filter(row=>row.id!==id);result={ok:true,item,message:"分类和文件夹动作已确认"};}else result={ok:true,item:{...item,recipients:["fixture@example.test"],cc:"legal@example.test",message_text:"您好，\n\n请查看以下项目与合同的最新信息。正文保持完整呈现，不影响列表行高。\n\n这是第二段内容，包含中文与 English 测试。\n\n> 引用邮件：\n> 上次约定的交付时间为本周五。"},provider_classification:item?.provider_classification,observability:[{kind:"provider_action",operation:"move",status:"succeeded",summary:"已移动并回读目标文件夹",provider_result_id:"fixture-receipt-1"}]};}
  else if(path.startsWith("/api/console/email/model-versions/"))result={ok:true,model:models.find(model=>model.model_id===decodeURIComponent(path.split("/").at(-1)!))};
  else throw new Error("Unmatched fixture request: "+method+" "+path);
  return new Response(JSON.stringify(result),{status:200,headers:{"Content-Type":"application/json"}});
};
createRoot(document.getElementById("root")!).render(<BrowserRouter><div className="console-root"><div style={{padding:12,background:"var(--accent-soft)"}}>本地视觉测试数据 · 所有 API 操作仅作用于内存</div><EmailPage/></div></BrowserRouter>);
